name: input context # same like jenkins input

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "choose environment"
        required: true
        default: "DEV"
  push:
    branches: ["main"]

jobs:
  node build: #job1
    runs-on: ubuntu-latest
    steps:
      - name: trail command run
        run: echo "Trail run command"