# used to run multiple variations like nodejs versions of a job parallelly 
# without writing multiple steps.

name: Node.js CI 

on:
  push:
    branches: ["main"]

jobs:
  node build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      
      - name: use node.js
        uses: action/setup-node@v3 
        with:
          node-version: ${{ matrix.node-version}} #dynamic version
      - run: npm test
      - run: npm Install
