name: Need context # just like wait=true in Jenkins; if other job is success then only next job runs

on:
  push:
    branches: ["main"]

jobs:
  nodebuild: # job1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: nodebuild # ensures deploy waits for nodebuild to succeed
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to S3
        run: echo "deploying to s3"
