name: Need context # just like wait=true in jenkins; if other job is success then only next job runs


on:
  push:
    branches: ["main"]

jobs:
  nodeBuild: #job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: npm install
      - name: run test
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: nodeBuild # this make sure deploy job waits for node build job
    steps:
      - uses: actions/checkout@v4
      - name: deploy to s3
        run: echo " deploying to s3"