name: Deploy
on:
  push:
    branches: [ "main" ]

jobs:
  nodeBuild: # job1
    runs-on: ubuntu-latest
    outputs:
      val: ${{ steps.step1.outputs.val1 }} # correct reference

    steps:
      - name: output
        id: step1
        run: |
          echo "val1=raghu" >> $GITHUB_OUTPUT
          echo "val2=rohan" >> $GITHUB_OUTPUT

      - name: display
        run: echo "Step1 val1 = ${{ steps.step1.outputs.val1 }}"

  test:
    needs: nodeBuild   # must match job id
    runs-on: ubuntu-latest
    steps:
      - name: use job output
        run: echo "job output = ${{ needs.nodeBuild.outputs.val }}"