name: Node.js CI 

on:
  push:
    branches: ["main"]

jobs:
  nodebuild:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false #even if one job fails , dont stop the workflow , if true , it fails the workflow
      matrix:
        node-version: [16, 18, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: use node.js
        uses: actions/setup-node@v3 
        with:
          node-version: ${{ matrix.node-version }} #dynamic version
      - run: npm install
      - run: npm test
      

